### ISSUE TITLE
from nskit import *

### ISSUE THREAD

**Issue by KOarch** [Arty40m/nskit#1]
rna_sequence = extract_rna_sequence_from_pdb(pdb_file_path)
dot_bracket_notation = get_dot_bracket_notation(rna_sequence)
na = NA(rna_sequence, dot_bracket_notation)
na

result:
GAAUUGCGG
....((((.....(((((((...
Why can't I get a svg?

**Comment by Arty40m** [comment]
Since nskit is not released yet, tutorial may be outdated (it is).
SVG drawing works in the latest commit, but in case jupyterlab does not represent svg correctly consider calling IPython methods directly.

import nskit as nsk
from IPython.display import display_svg, SVG

na = nsk.NA('AGUUGGACGAACAUUAAACGUCCGGCUAGCCAAAAAAAAAAAAAAAAAAAAAAACCCAAUAGGC', '.(((..((((..((.[[.)).{{{.]]..((((.}}}..[[..))))..)).]]..))..))).')
display_svg(SVG(na.draw()))
